### GET todos
GET https://kj8ib2n8eb.execute-api.us-east-1.amazonaws.com/prod/todos

### POST new todo
POST https://kj8ib2n8eb.execute-api.us-east-1.amazonaws.com/prod/todos
Content-Type: application/json

{
  "task": "Learn Server 2"
}

### GET todo
GET https://kj8ib2n8eb.execute-api.us-east-1.amazonaws.com/prod/todos/2024-09-25T16:48:12.792Z
Content-Type: application/json

### UPDATE todo
PUT https://kj8ib2n8eb.execute-api.us-east-1.amazonaws.com/prod/todos/2024-09-25T16:48:12.792Z
Content-Type: application/json

{
  "task": "Learn Server UPDATED"
}


### DELETE todo
DELETE https://kj8ib2n8eb.execute-api.us-east-1.amazonaws.com/prod/todos/2024-09-25T16:42:26.578Z
